# steps:
#   - name: 'gcr.io/cloud-builders/gcloud'
#     args:
#       - compute
#       - ssh
#       - ubuntu@dockercicd
#       - --zone=us-east4-a
#       - --command=cd /home/faithproject424/cicd && bash ./deploy.sh

# timeout: '1200s'

# options:
#   defaultLogsBucketBehavior: REGIONAL_USER_OWNED_BUCKET

######

steps:
- name: 'gcr.io/cloud-builders/gcloud'
  entrypoint: 'bash'
  args:
    - '-c'
    - |
      # Replace these variables with your VM details
      VM_NAME="dockercicd"
      ZONE="us-east4-a"
      PROJECT_ID=$(gcloud config get-value project)

      # Example: copy files to VM
      gcloud compute scp --recurse ./app-dir $VM_NAME:~/app-dir --zone=$ZONE --project=$PROJECT_ID

      # Run commands remotely on the VM
      gcloud compute ssh $VM_NAME --zone=$ZONE --project=$PROJECT_ID --command="
        cd ~/app-dir && 
        ./deploy.sh
      "
timeout: 1200s


options:
  defaultLogsBucketBehavior: REGIONAL_USER_OWNED_BUCKET



