# steps:
#   - name: 'gcr.io/cloud-builders/gcloud'
#     args:
#       - compute
#       - ssh
#       - ubuntu@dockercicd
#       - --zone=us-east4-a
#       - --command=cd /home/faithproject424/cicd && bash ./deploy.sh

# timeout: '1200s'

# options:
#   defaultLogsBucketBehavior: REGIONAL_USER_OWNED_BUCKET

######

steps:
  # copy everything in workspace to the VM
  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        # go to the build workspace (where your code lives)
        cd $BUILD_WORKSPACE_DIR
        # copy all files & folders (non-hidden) to the VM target dir
        gcloud compute scp --recurse ./* ubuntu@dockercicd:/home/faithproject424/cicd --zone=us-east4-a

  # run your deploy script
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - compute
      - ssh
      - ubuntu@dockercicd
      - --zone=us-east4-a
      - --command=cd /home/faithproject424/cicd && bash ./deploy.sh

timeout: '1200s'

options:
  defaultLogsBucketBehavior: REGIONAL_USER_OWNED_BUCKET






