steps:
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - compute
      - ssh
      - ubuntu@dockercicd  # VM name
      - --zone=us-east4-a
      - --command=cd /home/faithproject424 && bash ./deploy.sh

timeout: '1200s'


