# steps:
#   - name: 'gcr.io/cloud-builders/gcloud'
#     args:
#       - compute
#       - ssh
#       - ubuntu@dockercicd
#       - --zone=us-east4-a
#       - --command=cd /home/faithproject424/cicd && bash ./deploy.sh

# timeout: '1200s'

# options:
#   defaultLogsBucketBehavior: REGIONAL_USER_OWNED_BUCKET

######

steps:
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - compute
      - scp
      - --recurse
      - /workspace/*
      - ubuntu@dockercicd:/home/faithproject424/cicd
      - --zone=us-east4-a

  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - compute
      - ssh
      - ubuntu@dockercicd
      - --zone=us-east4-a
      - --command=cd /home/faithproject424/cicd && bash ./deploy.sh

