# steps:
#   - name: 'gcr.io/cloud-builders/gcloud'
#     args:
#       - compute
#       - ssh
#       - ubuntu@dockercicd
#       - --zone=us-east4-a
#       - --command=cd /home/faithproject424/cicd && bash ./deploy.sh

# timeout: '1200s'

# options:
#   defaultLogsBucketBehavior: REGIONAL_USER_OWNED_BUCKET

######

steps:
- name: 'gcr.io/cloud-builders/gcloud'
  entrypoint: 'bash'
  args:
    - '-c'
    - |
      # Directly use values without declaring variables
      gcloud compute scp --recurse ./app-dir dockercicd:~/app-dir --zone=us-east4-a --project=devops-459203

      gcloud compute ssh dockercicd --zone=us-east4-a --project=devops-459203 --command="
        cd ~/app-dir &&
        ./deploy.sh
      "
timeout: 1200s
options:
  defaultLogsBucketBehavior: REGIONAL_USER_OWNED_BUCKET




